import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/NavigationBar/NavigationBar";
import BottomNavigation from "./components/BottomNavigation/BottomNavigation";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight : ["400"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.className} ${geistSans.variable} ${geistMono.variable}`}>
        <NavigationBar/>
        {children}
        <BottomNavigation/>
      </body>
    </html>
  );
}
